server:
  port: 8080

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 25
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

indexing-settings:
  sites:
    - url: https://dombulgakova.ru
      name: DomBulgakova/
    - url: https://nikoartgallery.com
      name: NikoArtGallery
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://www.svetlovka.ru/
#      name: RadioMV
#    - url: https://volochek.life
#      name: VolochekLife

jsoup-settings:
  userAgent: KirillSearchEngine
  referrer: https://www.google.com/

search-service:
  percentOfPages: 0.7
  numberOfSymbols: 300

logging:
  config: logback.xml